[package]
name = "flash_cards"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs = "0.3.2"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
slint = "1.12.1"
tokio = { version = "1.45.1", features = ["full"] }
